### ISSUE TITLE
[14.0] Can not assign storage.backend to storage.backend.image

### ISSUE THREAD

**Issue by Mat-moran** [OCA/storage#122]
There is not possibility to select backend during the creation of an image in storage.backend.image. 
![image](https://user-images.githubusercontent.com/4810013/134750064-1caf3751-cd05-4a6c-952a-4ffe211c58af.png)

Is this the correct behaviour? I soppose not because you can have different storage.backends, but I am not sure.

When I try to add it with a server action I get the next error:
```
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

```

**Comment by Mat-moran** [comment]
This error is because a backend is already assign and I am trying to force it.

```
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```


from my POV It may be better to give an advice if you try to change the backend if it is already set.

We will do a PR soon to try to solve this issue.

**Comment by Mat-moran** [comment]
It seems that the phylosohy of the module is to set up the storage.backend as a parameter in the system parameters for all the images, so I understand that a PR with this functionality is not needed.

I close this.
