### ISSUE TITLE
[13.0] Dependency boto3 issue storage_backend_s3 

### ISSUE THREAD

**Issue by HviorForgeFlow** [OCA/storage#67]
Installing boto3 pip dependency with no version assigned is using version boto3==1.16.2
This version required urllib3>=1.25.4 
requests pip package has a dependency that does not allow to use urllib3 version higher than 1.25
```
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->odoo==13.0) (2020.6.20)
Collecting urllib3<1.25,>=1.21.1
  Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
``` 
Once you try to update storage_backend_s3 module you will get:
```
NameError: name 'boto3' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 419, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4104, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1374, in _load_records_write
    super(View, self)._load_records_write(values)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4042, in _load_records_write
    self.write(values)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/auto/addons/component_event/models/base.py", line 106, in write
    result = super(Base, self).write(vals)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3600, in write
    fields[0].determine_inverse(real_recs)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1118, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/auto/addons/component_event/models/base.py", line 106, in write
    result = super(Base, self).write(vals)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3595, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1201, in _validate_fields
    check(self)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 394, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 966, in postprocess_and_fields
    fields = Model.fields_get(None)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 2805, in fields_get
    description = field.get_description(self.env)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 724, in get_description
    value = value(env)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 2225, in _description_selection
    return getattr(env[self.model_name], selection)()
  File "/opt/odoo/auto/addons/storage_backend_s3/models/storage_backend.py", line 65, in _selection_aws_region
    session = boto3.session.Session()
odoo.tools.convert.ParseError: "name 'boto3' is not defined" while parsing /opt/odoo/auto/addons/storage_backend_s3/views/backend_storage_view.xml:2, near
<odoo>
    <record id="storage_backend_view_form" model="ir.ui.view">
        <field name="model">storage.backend</field>
        <field name="inherit_id" ref="storage_backend.storage_backend_view_form"/>
        <field name="arch" type="xml">
            <group name="config" position="after">
                <group name="Amazon S3" string="Amazon S3" attrs="{'invisible': [('backend_type', '!=', 'amazon_s3')]}">
                    <group>
                        <field name="aws_host"/>
                        <field name="aws_access_key_id" attrs="{'required': [('backend_type', '=', 'amazon_s3')]}"/>
                        <field name="aws_secret_access_key" attrs="{'required': [('backend_type', '=', 'amazon_s3')], 'readonly':[('backend_type', '!=', 'amazon_s3')]}"/>
                        <field name="aws_bucket" attrs="{'required': [('backend_type', '=', 'amazon_s3')]}"/>
                        <field name="aws_cache_control"/>
                        <field name="aws_file_acl"/>
                    </group>
                    <group>
                        <field name="aws_region" widget="radio" attrs="{'required': [('backend_type', '=', 'amazon_s3')]}"/>
                        <field name="aws_other_region" attrs="{'invisible': [('aws_region', '!=', 'other')]}"/>
                    </group>
                </group>
            </group>
        </field>
    </record>
</odoo>
```
That error is raise when importing boto3 library:
```
Python 3.6.12 (default, Oct 13 2020, 21:45:01) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 30, in <module>
    import botocore.credentials
  File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/local/lib/python3.6/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/local/lib/python3.6/site-packages/botocore/awsrequest.py", line 25, in <module>
    import botocore.utils
  File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 30, in <module>
    from urllib3.util.url import IPV6_ADDRZ_RE
ImportError: cannot import name 'IPV6_ADDRZ_RE'
```
Issue solved downgrading version to boto3==1.15.17

https://github.com/boto/botocore/issues/2187

FYI @sebastienbeau @rvalyi @rousseldenis @simahawk

**Comment by rousseldenis** [comment]
@sebastienbeau I think we need to add an entry here : https://github.com/OCA/storage/blob/13.0/setup/storage_backend_s3/setup.py that requires boto3<= 1.15.17

**Comment by sbidoul** [comment]
Note that with pip 20.3 due end of next week if all goes according to plan, conflicting dependencies will become hard installation errors.
